name: CICD Build
on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: |
          git fetch --tags --force  # Retrieve annotated tags.

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Test
        run: |
          go test ./...
